#[[plugins]]
#repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add='source ~/.config/nvim/rc/plugins/lightline.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add='source ~/.config/nvim/rc/plugins/lightline.vim'

[[plugins]]
repo = 'taigacute/spaceline.vim'

#[[plugins]]
#repo = 'bling/vim-airline'
#hook_add='source ~/.config/nvim/rc/plugins/vim-airline.vim'

#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#hook_add = '''
#let g:airline_theme='wombat'
#'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'rking/ag.vim'
hook_add = 'source ~/.config/nvim/rc/plugins/search.vim'

[[plugins]]
repo = 'sbdchd/neoformat'
hook_add = 'source ~/.config/nvim/rc/plugins/neoformat.vim'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.config/nvim/rc/plugins/fzf.vim'


[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'mhinz/vim-startify'
depends = 'vim-devicons'
hook_add ='source ~/.config/nvim/rc/plugins/startify.vim'
hook_post_source = '''
function! StartifyEntryFormat()
    return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
endfunction
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install'
hook_add = '''
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'
let g:coc_status_error_sign = '•'
let g:coc_status_warning_sign = '•'
'''
